/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoring_apps;

import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDb;

/**
 *
 * @author USER
 */
public class ReimbursementListFrame extends javax.swing.JFrame {

    private final Connection conn = new KoneksiDb().connect();
    private DefaultTableModel reimbursementTableModel;
    private String lastSearchKeyword = "";

    /**
     * Creates new form ReimbursementListFrame
     */
    public ReimbursementListFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Navigation.bind(sidebarMenu1, this);
        setupReimbursementListFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnEdit = new components.RoundedButton();
        userProfileCard1 = new components.UserProfileCard();
        sidebarMenu1 = new components.SidebarMenu();
        pageTitle1 = new components.PageTitle();
        searchBox1 = new components.SearchBox();
        btnViewReport = new components.RoundedButton();
        btnNew = new components.RoundedButton();
        btnBack = new components.RoundedButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIST REIMBURSEMENT");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        pageTitle1.setText("USER");

        searchBox1.setText("Cari...");

        btnViewReport.setText("View Report");

        btnNew.setText("+ New Administration");

        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.setButtonColor(new java.awt.Color(217, 217, 217));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userProfileCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidebarMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pageTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userProfileCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {                                        
        openSelectedReimbursement();
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        loadReimbursementData(getSearchKeyword());
    }                                        

    private void setupReimbursementListFrame() {
        pageTitle1.setText("LIST REIMBURSEMENT");
        btnNew.setText("+ New Reimbursement");
        jButton1.setText("CARI");

        setupReimbursementTable();
        setupButtonActions();
        setupSearchAction();
        loadReimbursementData("");
    }

    private void setupButtonActions() {
        btnNew.addActionListener(e -> {
            new ReimbursementFormFrame().setVisible(true);
            dispose();
        });

        btnViewReport.addActionListener(e -> viewSelectedReport());

        btnBack.addActionListener(e -> {
            new Dashboard().setVisible(true);
            dispose();
        });

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    openSelectedReimbursement();
                }
            }
        });
    }

    private void setupSearchAction() {
        searchBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if ("Cari...".equalsIgnoreCase(searchBox1.getText().trim())) {
                    searchBox1.setText("");
                    lastSearchKeyword = "";
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (searchBox1.getText().trim().isEmpty()) {
                    searchBox1.setText("Cari...");
                    lastSearchKeyword = "";
                    loadReimbursementData("");
                }
            }
        });

        Timer searchTimer = new Timer(400, e -> {
            String keyword = getSearchKeyword();

            if (!keyword.equals(lastSearchKeyword)) {
                lastSearchKeyword = keyword;
                loadReimbursementData(keyword);
            }
        });

        searchTimer.start();
    }

    private String getSearchKeyword() {
        String keyword = searchBox1.getText();

        if (keyword == null) {
            return "";
        }

        keyword = keyword.trim();

        if ("Cari...".equalsIgnoreCase(keyword)) {
            return "";
        }

        return keyword;
    }

    private void setupReimbursementTable() {
        reimbursementTableModel = new DefaultTableModel(
            new Object[]{
                "ID",
                "No Reimbursement",
                "Project ID",
                "Hari",
                "Tanggal",
                "Perihal",
                "PJ",
                "Jumlah Item",
                "Preview Uraian",
                "Total Akhir"
            },
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable1.setModel(reimbursementTableModel);
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));

        setTableColumnWidth();
        hideIdColumn();
    }

    private void setTableColumnWidth() {
        if (jTable1.getColumnModel().getColumnCount() < 10) {
            return;
        }

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(220);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(130);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(260);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(140);
    }

    private void hideIdColumn() {
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        }
    }

    private void loadReimbursementData(String keyword) {
        if (reimbursementTableModel == null) {
            return;
        }

        reimbursementTableModel.setRowCount(0);

        String search = keyword == null ? "" : keyword.trim();

        if ("Cari...".equalsIgnoreCase(search)) {
            search = "";
        }

        String like = "%" + search + "%";

        String sql = "SELECT "
                + "r.id, "
                + "COALESCE(r.reimbursement_no, CONCAT('REIM-', r.id)) AS reimbursement_no, "
                + "r.project_id, "
                + "r.hari, "
                + "r.tanggal, "
                + "r.hal, "
                + "r.pj, "
                + "COUNT(ri.id) AS jumlah_item, "
                + "COALESCE(GROUP_CONCAT(ri.uraian ORDER BY ri.id ASC SEPARATOR ', '), '') AS uraian_preview, "
                + "COALESCE(NULLIF(r.total_akhir, 0), SUM(ri.jumlah), 0) AS total_akhir "
                + "FROM reimbursement r "
                + "LEFT JOIN reimbursement_items ri ON ri.reimbursement_id = r.id "
                + "WHERE (? = '' "
                + "OR COALESCE(r.reimbursement_no, '') LIKE ? "
                + "OR CAST(r.project_id AS CHAR) LIKE ? "
                + "OR COALESCE(r.hari, '') LIKE ? "
                + "OR CAST(r.tanggal AS CHAR) LIKE ? "
                + "OR COALESCE(r.hal, '') LIKE ? "
                + "OR COALESCE(r.pj, '') LIKE ? "
                + "OR EXISTS ("
                + "    SELECT 1 FROM reimbursement_items ris "
                + "    WHERE ris.reimbursement_id = r.id "
                + "    AND COALESCE(ris.uraian, '') LIKE ?"
                + ")) "
                + "GROUP BY r.id, r.reimbursement_no, r.project_id, r.hari, r.tanggal, r.hal, r.pj, r.total_akhir "
                + "ORDER BY r.id DESC";

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, search);
            ps.setString(2, like);
            ps.setString(3, like);
            ps.setString(4, like);
            ps.setString(5, like);
            ps.setString(6, like);
            ps.setString(7, like);
            ps.setString(8, like);

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    reimbursementTableModel.addRow(new Object[]{
                        rs.getInt("id"),
                        nullToEmpty(rs.getString("reimbursement_no")),
                        rs.getInt("project_id"),
                        nullToEmpty(rs.getString("hari")),
                        nullToEmpty(rs.getString("tanggal")),
                        nullToEmpty(rs.getString("hal")),
                        nullToEmpty(rs.getString("pj")),
                        rs.getInt("jumlah_item"),
                        nullToEmpty(rs.getString("uraian_preview")),
                        bigDecimalToString(rs.getBigDecimal("total_akhir"))
                    });
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                "Gagal mengambil data reimbursement:\n" + e.getMessage()
            );
        }
    }

    private Integer getSelectedReimbursementId() {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data reimbursement terlebih dahulu.");
            return null;
        }

        int modelRow = jTable1.convertRowIndexToModel(selectedRow);
        Object idValue = reimbursementTableModel.getValueAt(modelRow, 0);

        try {
            return Integer.parseInt(String.valueOf(idValue));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ID reimbursement tidak valid.");
            return null;
        }
    }

    private void openSelectedReimbursement() {
        Integer reimbursementId = getSelectedReimbursementId();

        if (reimbursementId == null) {
            return;
        }

        ReimbursementFormFrame form = new ReimbursementFormFrame();

        try {
            Method method = ReimbursementFormFrame.class.getMethod("loadReimbursementById", Integer.class);
            method.invoke(form, reimbursementId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Form dibuka, tapi data belum otomatis termuat.\n"
                + "Pastikan ReimbursementFormFrame punya method:\n"
                + "public void loadReimbursementById(Integer reimbursementId)"
            );
        }

        form.setVisible(true);
        dispose();
    }

    private void viewSelectedReport() {
        Integer reimbursementId = getSelectedReimbursementId();

        if (reimbursementId == null) {
            return;
        }

        String headerSql = "SELECT "
                + "COALESCE(reimbursement_no, CONCAT('REIM-', id)) AS reimbursement_no, "
                + "project_id, hari, tanggal, hal, pj, total_akhir "
                + "FROM reimbursement WHERE id = ?";

        String itemSql = "SELECT uraian, qty, satuan, harga_satuan, jumlah "
                + "FROM reimbursement_items WHERE reimbursement_id = ? ORDER BY id ASC";

        try (PreparedStatement headerPs = conn.prepareStatement(headerSql);
             PreparedStatement itemPs = conn.prepareStatement(itemSql)) {

            headerPs.setInt(1, reimbursementId);

            try (ResultSet rs = headerPs.executeQuery()) {
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "Data reimbursement tidak ditemukan.");
                    return;
                }

                StringBuilder report = new StringBuilder();

                report.append("No Reimbursement : ").append(nullToEmpty(rs.getString("reimbursement_no"))).append("\n")
                        .append("Project ID       : ").append(rs.getInt("project_id")).append("\n")
                        .append("Hari             : ").append(nullToEmpty(rs.getString("hari"))).append("\n")
                        .append("Tanggal          : ").append(nullToEmpty(rs.getString("tanggal"))).append("\n")
                        .append("Perihal          : ").append(nullToEmpty(rs.getString("hal"))).append("\n")
                        .append("PJ               : ").append(nullToEmpty(rs.getString("pj"))).append("\n")
                        .append("Total Akhir      : ").append(bigDecimalToString(rs.getBigDecimal("total_akhir"))).append("\n\n")
                        .append("ITEM REIMBURSEMENT\n")
                        .append("--------------------------------------------------\n");

                itemPs.setInt(1, reimbursementId);

                try (ResultSet itemRs = itemPs.executeQuery()) {
                    int no = 1;

                    while (itemRs.next()) {
                        report.append(no++).append(". ")
                                .append(nullToEmpty(itemRs.getString("uraian")))
                                .append(" | Qty: ").append(itemRs.getInt("qty"))
                                .append(" | Satuan: ").append(nullToEmpty(itemRs.getString("satuan")))
                                .append(" | Nominal: ").append(bigDecimalToString(itemRs.getBigDecimal("harga_satuan")))
                                .append(" | Total: ").append(bigDecimalToString(itemRs.getBigDecimal("jumlah")))
                                .append("\n");
                    }
                }

                JOptionPane.showMessageDialog(
                    this,
                    report.toString(),
                    "View Report Reimbursement",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                "Gagal mengambil report reimbursement:\n" + e.getMessage()
            );
        }
    }

    private String nullToEmpty(String value) {
        return value == null ? "" : value;
    }

    private String bigDecimalToString(BigDecimal value) {
        return value == null ? "0" : value.toPlainString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReimbursementListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private components.RoundedButton btnBack;
    private components.RoundedButton btnEdit;
    private components.RoundedButton btnNew;
    private components.RoundedButton btnViewReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private components.PageTitle pageTitle1;
    private components.SearchBox searchBox1;
    private components.SidebarMenu sidebarMenu1;
    private components.UserProfileCard userProfileCard1;
    // End of variables declaration                   
}