/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoring_apps;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultCellEditor;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.table.TableCellRenderer;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksi.KoneksiDb;
import components.PlusIcon;

/**
 *
 * @author USER
 */
public class ReimbursementListFrame extends javax.swing.JFrame {

    private static final int ID_COLUMN = 0;
    private static final int ACTION_COLUMN = 10;

    private final Connection conn = new KoneksiDb().connect();
    private DefaultTableModel reimbursementTableModel;
    private Timer searchTimer;
    private String lastSearchKeyword = "";



    /**
     * Creates new form ReimbursementListFrame
     */
    public ReimbursementListFrame() {
        initComponents();
        searchBox1.setText("");
        setLocationRelativeTo(null);
        Navigation.bind(sidebarMenu1, this);
        setupReimbursementListFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProfileCard1 = new components.UserProfileCard();
        sidebarMenu1 = new components.SidebarMenu();
        pageTitle1 = new components.PageTitle();
        searchBox1 = new components.SearchBox();
        btnViewReport = new components.RoundedButton();
        btnNew = new components.RoundedButton();
        tblReimbursement = new components.RoundedTablePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIST REIMBURSEMENT");
        setMinimumSize(new java.awt.Dimension(1200, 800));

        pageTitle1.setText("USER");

        btnViewReport.setText("View Report");

        btnNew.setText("+ New Administration");



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userProfileCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidebarMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pageTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(searchBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tblReimbursement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userProfileCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(tblReimbursement, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupReimbursementListFrame() {
        pageTitle1.setText("LIST REIMBURSEMENT");
        btnNew.setText("Tambah");
        btnNew.setIcon(new PlusIcon(16));
        btnNew.setButtonColor(components.RoundedColors.PRIMARY);
        btnNew.setForeground(java.awt.Color.WHITE);
        searchBox1.setText("");

        setupButtonActions();
        setupReimbursementTable();
        setColumnWidths();
        setupSearchAction();
        loadReimbursementData("");
    }

    private void setupButtonActions() {
        btnNew.addActionListener(e -> {
            new ReimbursementFormFrame().setVisible(true);
            dispose();
        });

//        btnViewReport.addActionListener(e -> viewSelectedReport());


        
        // Edit & Delete action diatur di setupReimbursementTable()
    }

    private void setupSearchAction() {
        searchTimer = new Timer(300, e -> {
            String keyword = getSearchKeyword();

            if (!keyword.equals(lastSearchKeyword)) {
                lastSearchKeyword = keyword;
                loadReimbursementData(keyword);
            }
        });
        searchTimer.setRepeats(false);

        searchBox1.getTextField().getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchTimer.restart();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchTimer.restart();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchTimer.restart();
            }
        });
    }

    private String getSearchKeyword() {
        String keyword = searchBox1.getText();

        if (keyword == null) {
            return "";
        }

        keyword = keyword.trim();

        if ("Cari...".equalsIgnoreCase(keyword)) {
            return "";
        }

        return keyword;
    }

    private void setupReimbursementTable() {
        tblReimbursement.setEditAction(
            "/image/edit.png",
            new components.RoundedTablePanel.ActionClickListener() {
                @Override
                public void onActionClick(int row) {
                    openSelectedReimbursement(row);
                }
            }
        );

        tblReimbursement.setDeleteAction(
            "/image/delete.png",
            new components.RoundedTablePanel.ActionClickListener() {
                @Override
                public void onActionClick(int row) {
                    Integer id = getSelectedReimbursementId(row);
                    if (id == null) return;
                    int confirm = JOptionPane.showConfirmDialog(
                        ReimbursementListFrame.this,
                        "Yakin ingin menghapus reimbursement ini?\nData yang dihapus tidak dapat dikembalikan.",
                        "Konfirmasi Hapus",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                    );
                    if (confirm == JOptionPane.YES_OPTION) {
                        deleteReimbursement(id, row);
                    }
                }
            }
        );

        Object[] columns = {
                "ID",
                "No Reimbursement",
                "Project ID",
                "Hari",
                "Tanggal",
                "Perihal",
                "PJ",
                "Jumlah Item",
                "Preview Uraian",
                "Total Akhir"
            };
        tblReimbursement.setTableData(new Object[0][columns.length], columns);
        reimbursementTableModel = tblReimbursement.getModel();
    }

    private void deleteReimbursement(int id, int row) {
        try {
            java.sql.Connection c = new koneksi.KoneksiDb().connect();
            java.sql.PreparedStatement ps = c.prepareStatement(
                "DELETE FROM reimbursement WHERE id = ?");
            ps.setInt(1, id);
            int result = ps.executeUpdate();
            if (result > 0) {
                reimbursementTableModel.removeRow(row);
                JOptionPane.showMessageDialog(ReimbursementListFrame.this,
                    "Reimbursement berhasil dihapus.", "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(ReimbursementListFrame.this,
                    "Data tidak ditemukan.", "Gagal",
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ReimbursementListFrame.this,
                "Gagal menghapus: " + e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void setColumnWidths() {
        JTable table = tblReimbursement.getTable();
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (Component comp : tblReimbursement.getComponents()) {
            if (comp instanceof JScrollPane) {
                JScrollPane scroll = (JScrollPane) comp;
                scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
                scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
                break;
            }
        }

        int[] widths = {
           130, 210, 55, 150, 100, 170, 100, 100, 140, 90, 70
        };

        for (int i = 0; i < widths.length && i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
            table.getColumnModel().getColumn(i).setMinWidth(widths[i]);
            table.getColumnModel().getColumn(i).setMaxWidth(widths[i]);
        }

        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);
        int aksiCol = table.getColumnCount() - 1;
        for (int i = 0; i < aksiCol; i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(center);
        }
    }


    private Icon loadEditIcon() {
        java.net.URL iconUrl = getClass().getResource("/image/icon/edit.png");
        if (iconUrl == null) {
            return null;
        }
        ImageIcon icon = new ImageIcon(iconUrl);
        java.awt.Image image = icon.getImage().getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(image);
    }

    private void loadReimbursementData(String keyword) {
        if (reimbursementTableModel == null) {
            return;
        }

        reimbursementTableModel.setRowCount(0);

        String search = keyword == null ? "" : keyword.trim();

        if ("Cari...".equalsIgnoreCase(search)) {
            search = "";
        }

        String like = "%" + search + "%";

        String sql = "SELECT "
                + "r.id, "
                + "COALESCE(r.reimbursement_no, CONCAT('REIM-', r.id)) AS reimbursement_no, "
                + "r.project_id, "
                + "r.hari, "
                + "r.tanggal, "
                + "r.hal, "
                + "r.pj, "
                + "COUNT(ri.id) AS jumlah_item, "
                + "COALESCE(GROUP_CONCAT(ri.uraian ORDER BY ri.id ASC SEPARATOR ', '), '') AS uraian_preview, "
                + "COALESCE(NULLIF(r.total_akhir, 0), SUM(ri.jumlah), 0) AS total_akhir "
                + "FROM reimbursement r "
                + "LEFT JOIN reimbursement_items ri ON ri.reimbursement_id = r.id "
                + "LEFT JOIN project p ON p.id = r.project_id "
                + "WHERE (? = '' "
                + "OR COALESCE(r.reimbursement_no, '') LIKE ? "
                + "OR CAST(r.project_id AS CHAR) LIKE ? "
                + "OR COALESCE(p.nama, '') LIKE ? "
                + "OR COALESCE(p.ta, '') LIKE ? "
                + "OR COALESCE(p.sub_perusahaan, '') LIKE ? "
                + "OR COALESCE(p.jenis, '') LIKE ? "
                + "OR COALESCE(p.instansi, '') LIKE ? "
                + "OR COALESCE(r.hari, '') LIKE ? "
                + "OR CAST(r.tanggal AS CHAR) LIKE ? "
                + "OR COALESCE(r.hal, '') LIKE ? "
                + "OR COALESCE(r.pj, '') LIKE ? "
                + "OR EXISTS ("
                + "    SELECT 1 FROM reimbursement_items ris "
                + "    WHERE ris.reimbursement_id = r.id "
                + "    AND COALESCE(ris.uraian, '') LIKE ?"
                + ")) "
                + "GROUP BY r.id, r.reimbursement_no, r.project_id, r.hari, r.tanggal, r.hal, r.pj, r.total_akhir "
                + "ORDER BY r.id DESC";

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, search);
            for (int i = 2; i <= 13; i++) {
                ps.setString(i, like);
            }

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    reimbursementTableModel.addRow(new Object[]{
                        rs.getInt("id"),
                        nullToEmpty(rs.getString("reimbursement_no")),
                        rs.getString("project_id"),
                        nullToEmpty(rs.getString("hari")),
                        nullToEmpty(rs.getString("tanggal")),
                        nullToEmpty(rs.getString("hal")),
                        nullToEmpty(rs.getString("pj")),
                        rs.getInt("jumlah_item"),
                        nullToEmpty(rs.getString("uraian_preview")),
                        bigDecimalToString(rs.getBigDecimal("total_akhir")),
                        null
                    });
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                "Gagal mengambil data reimbursement:\n" + e.getMessage()
            );
        }
    }

    private Integer getSelectedReimbursementId(int row) {
        Object idValue = reimbursementTableModel.getValueAt(row, 0);

        try {
            return Integer.parseInt(String.valueOf(idValue));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ID reimbursement tidak valid.");
            return null;
        }
    }

    private void openSelectedReimbursement(int row) {
        openReimbursementById(getSelectedReimbursementId(row));
    }

    private void openReimbursementById(Integer reimbursementId) {
        if (reimbursementId == null) {
            return;
        }

        ReimbursementFormFrame form = new ReimbursementFormFrame();

        try {
            Method method = ReimbursementFormFrame.class.getMethod("loadReimbursementById", Integer.class);
            method.invoke(form, reimbursementId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Form dibuka, tapi data belum otomatis termuat.\n"
                + "Pastikan ReimbursementFormFrame punya method:\n"
                + "public void loadReimbursementById(Integer reimbursementId)"
            );
        }

        form.setVisible(true);
        dispose();
    }

//    private void viewSelectedReport() {
//        Integer reimbursementId = getSelectedReimbursementId();
//
//        if (reimbursementId == null) {
//            return;
//        }
//
//        String headerSql = "SELECT "
//                + "COALESCE(reimbursement_no, CONCAT('REIM-', id)) AS reimbursement_no, "
//                + "project_id, hari, tanggal, hal, pj, total_akhir "
//                + "FROM reimbursement WHERE id = ?";
//
//        String itemSql = "SELECT uraian, qty, satuan, harga_satuan, jumlah "
//                + "FROM reimbursement_items WHERE reimbursement_id = ? ORDER BY id ASC";
//
//        try (PreparedStatement headerPs = conn.prepareStatement(headerSql);
//             PreparedStatement itemPs = conn.prepareStatement(itemSql)) {
//
//            headerPs.setInt(1, reimbursementId);
//
//            try (ResultSet rs = headerPs.executeQuery()) {
//                if (!rs.next()) {
//                    JOptionPane.showMessageDialog(this, "Data reimbursement tidak ditemukan.");
//                    return;
//                }
//
//                StringBuilder report = new StringBuilder();
//
//                report.append("No Reimbursement : ").append(nullToEmpty(rs.getString("reimbursement_no"))).append("\n")
//                        .append("Project ID       : ").append(rs.getInt("project_id")).append("\n")
//                        .append("Hari             : ").append(nullToEmpty(rs.getString("hari"))).append("\n")
//                        .append("Tanggal          : ").append(nullToEmpty(rs.getString("tanggal"))).append("\n")
//                        .append("Perihal          : ").append(nullToEmpty(rs.getString("hal"))).append("\n")
//                        .append("PJ               : ").append(nullToEmpty(rs.getString("pj"))).append("\n")
//                        .append("Total Akhir      : ").append(bigDecimalToString(rs.getBigDecimal("total_akhir"))).append("\n\n")
//                        .append("ITEM REIMBURSEMENT\n")
//                        .append("--------------------------------------------------\n");
//
//                itemPs.setInt(1, reimbursementId);
//
//                try (ResultSet itemRs = itemPs.executeQuery()) {
//                    int no = 1;
//
//                    while (itemRs.next()) {
//                        report.append(no++).append(". ")
//                                .append(nullToEmpty(itemRs.getString("uraian")))
//                                .append(" | Qty: ").append(itemRs.getInt("qty"))
//                                .append(" | Satuan: ").append(nullToEmpty(itemRs.getString("satuan")))
//                                .append(" | Nominal: ").append(bigDecimalToString(itemRs.getBigDecimal("harga_satuan")))
//                                .append(" | Total: ").append(bigDecimalToString(itemRs.getBigDecimal("jumlah")))
//                                .append("\n");
//                    }
//                }
//
//                JOptionPane.showMessageDialog(
//                    this,
//                    report.toString(),
//                    "View Report Reimbursement",
//                    JOptionPane.INFORMATION_MESSAGE
//                );
//            }
//
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(
//                this,
//                "Gagal mengambil report reimbursement:\n" + e.getMessage()
//            );
//        }
//    }

    private class ActionButtonRenderer extends JButton implements TableCellRenderer {

        private final Icon editIcon;

        ActionButtonRenderer(Icon editIcon) {
            this.editIcon = editIcon;
            setFocusPainted(false);
            setBorderPainted(false);
            setContentAreaFilled(false);
            setOpaque(true);
            setHorizontalAlignment(SwingConstants.CENTER);
        }

        @Override
        public Component getTableCellRendererComponent(
                JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column
        ) {
            setIcon(editIcon);
            setText(editIcon == null ? "Edit" : "");
            setToolTipText("Edit Reimbursement");
            setBackground(isSelected ? table.getSelectionBackground() : Color.WHITE);
            setForeground(new Color(63, 61, 150));
            setFont(new Font("Segoe UI", Font.BOLD, 12));
            return this;
        }
    }

    private class ActionButtonEditor extends DefaultCellEditor {

        private final JButton button = new JButton();
        private Integer reimbursementId;

        ActionButtonEditor(JCheckBox checkBox, Icon editIcon) {
            super(checkBox);
            button.setIcon(editIcon);
            button.setText(editIcon == null ? "Edit" : "");
            button.setToolTipText("Edit Reimbursement");
            button.setFocusPainted(false);
            button.setBorderPainted(false);
            button.setContentAreaFilled(false);
            button.setHorizontalAlignment(SwingConstants.CENTER);
            button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            button.addActionListener(e -> {
                fireEditingStopped();
                openReimbursementById(reimbursementId);
            });
        }

        @Override
        public Component getTableCellEditorComponent(
                JTable table,
                Object value,
                boolean isSelected,
                int row,
                int column
        ) {
            int modelRow = table.convertRowIndexToModel(row);
            Object idValue = reimbursementTableModel.getValueAt(modelRow, ID_COLUMN);

            try {
                reimbursementId = Integer.parseInt(String.valueOf(idValue));
            } catch (Exception e) {
                reimbursementId = null;
            }

            button.setBackground(isSelected ? table.getSelectionBackground() : Color.WHITE);
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Edit";
        }
    }

    private String nullToEmpty(String value) {
        return value == null ? "" : value;
    }

    private String bigDecimalToString(BigDecimal value) {
        return value == null ? "0" : value.toPlainString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReimbursementListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReimbursementListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.RoundedButton btnNew;
    private components.RoundedButton btnViewReport;
    private components.PageTitle pageTitle1;
    private components.SearchBox searchBox1;
    private components.SidebarMenu sidebarMenu1;
    private components.RoundedTablePanel tblReimbursement;
    private components.UserProfileCard userProfileCard1;
    // End of variables declaration//GEN-END:variables
}